### ISSUE TITLE
Documentation is not available

### ISSUE THREAD

**Issue by sanjacob** [tu-graz-library/invenio-moodle#16]

**Comment by utnapischtim** [comment]
hello thank you for your request.

at the moment there is no intention to create an explicit documentation for it, as to my knowledge only I use it. 

do you have a use case in mind to use it?

which documentation do you would need?

**Comment by sanjacob** [comment]
@utnapischtim I was just letting you know, since you have a readthedocs link in the README. I am just trying out different moodle api clients, but nothing in particular.

**Comment by utnapischtim** [comment]
different moodle api clients for InvenioRDM?

and yeah i should remove that link. thanks for pointing that out

**Comment by sanjacob** [comment]
I honestly haven't heard of invenio, so I thought that was just the name of the library
